### PR TITLE
Adding folders

### PR DESCRIPTION
**Pull request by nani554**

### CODE REVIEW

**Comment by boro741** [comment]
bro u need to first pull from this main repo and then push

**Comment by nani554** [comment]
ohh sorry

**Comment by nani554** [comment]
i have sent a new pull request after fetching data from u ,do accept it

**Comment by boro741** [comment]
@nani554 your not supposed to put index.html inside a folder it breaks our link  https://boro741.github.io/FCC-Productivity-Timer/

Just review it again and send me the PR. After this I will start working on functionality and on some pages that is required.

**Pull request merged**
